version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: miles
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./packages/miles-api
    environment:
      PORT: 8080
      DATABASE_URL: postgresql://postgres:postgres@db:5432/miles?schema=public
      MILES_SHARED_SECRET: change-me
      MILES_ADMIN_TOKEN: admin-dev
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  web:
    build:
      context: ./packages/miles-web
      args:
        - VITE_API_BASE_URL=http://localhost:8080
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    depends_on:
      - api
    ports:
      - "8081:80"

